services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
    network_mode: host
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - data/
            - web/
            - tmp/
            - .git/

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    ports:
      - "23333:23333"
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - data/
            - tmp/
            - .git/
